/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dparish' at '6/1/15 3:53 PM' with Gradle 2.4
 *
 * @author dparish, @date 6/1/15 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
